Fixing last frontend details
starknet-id/sbtmaker.starknet.id pull request #26
Opened 2023-02-11 16:14 UTC by Marchand-Nicolas

2023-02-11 16:54 UTC, 0xBenaparte requested changes
Quelques petits trucs. 

Il faut vraiment que tu installes prettier là ça devient compliqué à lire haha.

2023-02-11 16:54 UTC, 0xBenaparte commented on src/components/UI/button.tsx
> +      onClick={onClick || (() => {})}
C'est quoi ce `|| (() => {})` 😭 ?

2023-02-11 16:54 UTC, 0xBenaparte commented on src/components/connection/networkSelector.tsx
> +export default function NetworkSelector({ isWrongNetwork, setIsWrongNetwork} : NetworkSelectorProps) {
Je ne comprend pas ce code et pq tu utilises une interface ici ? Peux tu m'expliquer ?

2023-02-11 16:54 UTC, 0xBenaparte commented on src/pages/index.tsx
>                }
C'est très difficile à lire là. 

Peux tu installer [prettier](https://www.npmjs.com/package/prettier) et le run sur tous les fichiers en faisant `prettier write`. 

Voici un tuto https://levelup.gitconnected.com/how-to-format-all-files-in-a-directory-with-prettier-5f0ff5f4ffb2

2023-02-11 17:34 UTC, Marchand-Nicolas commented on src/components/UI/button.tsx
> +      onClick={onClick || (() => {})}
D'accord, j'installe prettier.

> C'est quoi ce `|| (() => {})` 😭 ?

Ca c'est une erreur. Je le supprime.

2023-02-11 17:41 UTC, Marchand-Nicolas commented on src/components/connection/networkSelector.tsx
> +export default function NetworkSelector({ isWrongNetwork, setIsWrongNetwork} : NetworkSelectorProps) {
Comment ça ? Il me semble avoir extrait le code du composant navbar et injecté dans un composant. Pourquoi n'aurais-je pas du utiliser d'interface ?

2023-02-12 08:14 UTC, 0xBenaparte requested changes
Quelques petits trucs à changer. 

C'est quand meme bien mieux avec prettier tu trouves pas haha ?

2023-02-12 08:14 UTC, 0xBenaparte commented on public/fonts/montserrat/DESCRIPTION.en_us.html
> -The old posters and signs in the traditional <em>Montserrat</em> neighborhood of Buenos Aires inspired Julieta Ulanovsky to design this typeface and rescue the beauty of urban typography that emerged
Enlève la description de la font on en a pas besoin 👍

2023-02-12 08:14 UTC, 0xBenaparte commented on src/components/connection/networkSelector.tsx
> +}: NetworkSelectorProps) => {
là tu dois faire un truc comme ça :

```
NetworkSelector<NetworkSelectorProps> = ({  
    isWrongNetwork,
    setIsWrongNetwork,
  })
```

Regarde dans les autres composants on a fait comme ça :)

2023-02-12 08:14 UTC, 0xBenaparte commented on src/components/deploy.tsx
> +  setMenu,
Tu vois ici tu l'as bien fait 🔥

2023-02-12 08:14 UTC, 0xBenaparte commented on src/components/lookAndFeel.tsx
> +const LookAndFeel = ({ setTokenURI, setMenu, ...props }: LookAndFeelProps) => {
A changer ici

2023-02-12 08:14 UTC, 0xBenaparte commented on src/components/notifications/errorNotification.tsx
> +}: ErrorNotificationProps) {
A changer. 

Tu peux changer sur tous les composants avec la manière de faire que je t'ai montré au dessus ?

2023-02-12 08:14 UTC, 0xBenaparte commented on src/components/notifications/successNotification copy.tsx
> +export default function SuccessNotification({
Pareil. 

Je fais pas le reste tu as compris je pense 👍

2023-02-13 16:44 UTC, fricoben requested changes
Quelques problèmes de types et ça sera bon. 

On y est presque ! Je fais pas ça pour te faire chier mais pour que tu te rapproches le plus possible d'un code qu'on mettrait en production sur des grosses apps. 

Typer c'est chiant mais en gros ça sert à : 

1) La maintenance et la lisibilité du code sont améliorées. 
2) La détection des erreurs. 
3) La qualité du code est améliorée. 
4) La fiabilité du code est accrue. 

En utilisant `any` ou meme `[key: string]: any;` En tu utilisant abandonnes les avantages de Typescript et tu rajoutes memes des désavantages (parce que quand quelqu'un va débugger derrière toi il peut assumer que c'est bien typé alors que nan bref).

2023-02-13 16:44 UTC, fricoben commented on src/components/notifications/errorNotification.tsx
>  interface ErrorNotificationProps {
A transformer en type !

2023-02-13 16:44 UTC, fricoben commented on src/components/UI/loading.tsx
> +  [key: string]: any;
On veut que tu précises les props que tu vas envoyer. 

Si tu n'envoies rien alors tu ne met pas de type tout simplement :). 

La tu ne type rien du tout tu dis en gros ``On envoie un objet avec des propriétés de type any``

2023-02-13 16:44 UTC, fricoben commented on src/components/UI/loading.tsx
> +const Loading: FunctionComponent<LoadingProps> = (props) => {
Donc ici à changer aussi du coup (par rapport à ma remarque du type plus haut).

2023-02-13 16:44 UTC, fricoben commented on src/components/notifications/warningNotification.tsx
>  interface WarningNotificationProps {
pas d'interface

2023-02-13 16:44 UTC, fricoben commented on src/components/UI/textField.tsx
> +  [key: string]: any;
A enlever ici tu ne type rien. 

Pour la meme raison que mon commentaire précédent concernant le type :).

2023-02-13 16:44 UTC, fricoben commented on src/components/lookAndFeel.tsx
> +  [key: string]: any;
pas de ça 👀

2023-02-13 16:44 UTC, fricoben commented on src/components/UI/textField.tsx
> +  onChange?: (e: any) => void;
Pas de any ici je veux le vrai type de l'event haha

2023-02-13 16:44 UTC, fricoben commented on src/components/deploy.tsx
> +    const status = (data as any).status;
pas de as any :)

2023-02-13 16:44 UTC, fricoben commented on src/components/deploy.tsx
> +      setLoadingMessage((tx as any).code);
pas de as any ;)

2023-02-13 17:26 UTC, fricoben requested changes
Quelques dernières questions

2023-02-13 17:26 UTC, fricoben commented on src/components/UI/loading.tsx
> +const Loading: FunctionComponent = (props) => {
``= (props)``

Pas besoin de ça non plus bg car tu passes pas de props

2023-02-13 17:26 UTC, fricoben commented on src/pages/api/nft_storage.ts
> +  res: NextApiResponse<{ message: string; ipnft?: string; url?: string }>
A mettre dans un type ça. 

un type que tu met au dessus :)

2023-02-13 17:26 UTC, fricoben commented on src/components/UI/textField.tsx
> +  className?: string;
On ne passe pas des className en propriété sinon ça ouvre la porte à la dénaturalisation de ton composant. 

En gros avec un classname en props tu peux faire de ton composant ce pourquoi il n'est pas prévu et on veut bloquer ça au maximum.

De plus je vois `?:` partout ici, on l'utilise seulement quand une props n'est pas obligatoire. 

C'est le cas pour toutes celle là ici ?

2023-02-13 17:26 UTC, fricoben commented on src/components/UI/textField.tsx
> +  type?: string;
Il sert à quoi ce type ici ?

2023-02-13 17:26 UTC, fricoben commented on src/components/deploy.tsx
> +type InvokeFunctionResponseImproved = InvokeFunctionResponse & {
Pq tu as besoin de faire le & ici ? 

Pq la propriété `code` n'est pas dans le type de base ? C'est une réponse d'une query c'est ça ?

2023-02-13 17:34 UTC, Marchand-Nicolas commented on src/components/UI/textField.tsx
> +  className?: string;
Même si dans mon code il y a certaines de ces props que j'utilise à chaque fois, je les laisses optionnelles car à l'avenir elles pourraient ne pas être spécifiées, c'est pour rendre le composant modulaire, car en soit il est sensé fonctionner parfaitement sans ces props là. Mais je sais pas si c'est une bonne façon de faire par contre

2023-02-13 17:39 UTC, Marchand-Nicolas commented on src/components/UI/textField.tsx
> +  type?: string;
Type c'est pour le type de l'input (l'input pour le password est de type password, les autres sont par défaut)

2023-02-13 17:40 UTC, Marchand-Nicolas commented on src/components/deploy.tsx
> +type InvokeFunctionResponseImproved = InvokeFunctionResponse & {
Le type de la lib ne semble pas complet. Il ne contient que 'transaction_hash' alors que l'objet contient d'autres éléments tels que 'code'.

2023-02-13 17:42 UTC, fricoben commented on src/components/deploy.tsx
> +type InvokeFunctionResponseImproved = InvokeFunctionResponse & {
Ok ici le as any est finalement plus simple alors

2023-02-13 17:44 UTC, fricoben commented on src/components/UI/textField.tsx
> +  className?: string;
Ok c'est très bien je voulais vérifier que tu n'avais pas mis ?: par défaut partout sans comprendre !

2023-02-13 17:44 UTC, fricoben approved these changes
LFG

2023-02-13 17:44 UTC, merged